### ISSUE TITLE
Installing leads to error

### ISSUE THREAD

**Issue by kylebrowning** [cthos/atom-gitbook#18]
[Enter steps to reproduce below:]
1. Checkout package
2. make symlink in ~/.atom

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-gitbook](https://github.com/atom/atom-gitbook) package, v0.0.0
### Stack Trace

Failed to load the atom-gitbook package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/kylebrowning/Projects/atom-gitbook/lib/main.coffee:3:7)
    at Object.<anonymous> (/Users/kylebrowning/Projects/atom-gitbook/lib/main.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-gitbook, v0.0.0
browser-plus, v0.0.34
drupal, v1.8.0
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by kylebrowning** [comment]
Resolved by running `npm install` in atom-gitbook folder

**Comment by aquicthos** [comment]
@kylebrowning Opened #20 to cover installation instructions for development.
