### ISSUE TITLE
Parse book.json to find path to SUMMARY.md

### ISSUE THREAD

**Issue by CashWilliams** [cthos/atom-gitbook#35]
[Enter steps to reproduce below:]
1. install the package
2. open atom :)

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-gitbook](https://github.com/cthos/atom-gitbook) package, master
### Stack Trace

Failed to activate the atom-gitbook package

```
At path must be a string

TypeError: path must be a string
  at TypeError (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at SummaryParser.module.exports.SummaryParser.loadFromFile (/Users/cash/.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:22:19)
  at new SummaryParser (/Users/cash/.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:12:6)
  at Function.module.exports.SummaryParser.getInstance (/Users/cash/.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:9:34)
  at NavigationPane.module.exports.NavigationPane.getParser (/Users/cash/.atom/packages/atom-gitbook/lib/nav-pane.coffee:23:24)
  at NavigationPane.module.exports.NavigationPane.initialize (/Users/cash/.atom/packages/atom-gitbook/lib/nav-pane.coffee:18:6)
  at NavigationPane.View (/Users/cash/.atom/packages/atom-gitbook/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new NavigationPane (/Users/cash/.atom/packages/atom-gitbook/lib/nav-pane.coffee:9:3)
  at AtomGitbookView.module.exports.AtomGitbookView.getNavPane (/Users/cash/.atom/packages/atom-gitbook/lib/atom-gitbook-view.coffee:11:18)
  at AtomGitbookView.module.exports.AtomGitbookView.show (/Users/cash/.atom/packages/atom-gitbook/lib/atom-gitbook-view.coffee:15:52)
  at Object.module.exports.togglePanel (/Users/cash/.atom/packages/atom-gitbook/lib/main.coffee:83:21)
  at Object.module.exports.activate (/Users/cash/.atom/packages/atom-gitbook/lib/main.coffee:22:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:469:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:324:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:670:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:82:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-light"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-gitbook, v0.0.0
atom-material-syntax-light, v0.0.3
atom-material-ui, v0.6.2
formatter, v2.12.3

# Dev
No dev packages
```

**Comment by CashWilliams** [comment]
I see the problem.

I have my `SUMMARY.md` file in `/report/SUMMARY.md` which is where book.json points to. I created a `SUMMARY.md` file in the root and re-opened and did not get the error.

**Comment by CashWilliams** [comment]
So basically in `lib/helper/summary-parser.coffee`

```
  28   getFullFilepath: (directory) ->
  29     if fs.existsSync(path.join(directory, 'summary.md'))
  30       name = directory + '/summary.md'
  31     else if fs.existsSync(path.join(directory, '/SUMMARY.md'))
  32       name = directory + '/SUMMARY.md'
  33
  34     return name or false
```

returned `false` and is causing the issue.

**Comment by cthos** [comment]
@CashWilliams I'll just use this as the task issue. I've assigned this to Functional Alpha.

Thanks! :+1:
