### ISSUE TITLE
Error when moving chapter to the end

### ISSUE THREAD

**Issue by nagim** [cthos/atom-gitbook#49]
Hi,

I get an error if I want to move a chapter to the end of the TOC.

Here's the error message:

**Atom Version**: 1.3.1
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-gitbook](https://github.com/atom/atom-gitbook) package, v0.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'indent' of undefined

```
At /.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:94

TypeError: Cannot read property 'indent' of undefined
    at SummaryParser.module.exports.SummaryParser.addSection (file:///.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:71:16)
    at HTMLDivElement.<anonymous> (file:///.atom/packages/atom-gitbook/lib/nav-pane.coffee:72:22)
    at space-pen-div.jQuery.event.dispatch (\.atom\packages\atom-gitbook\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (\.atom\packages\atom-gitbook\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)
```
### Commands

```
     -9:34.4.0 markdown-preview:toggle (atom-text-editor.editor)
     -9:25.6.0 atom-gitbook:new-chapter (div.gitbook-navigation-pane)
  3x -9:06.5.0 markdown-preview:toggle (atom-text-editor.editor)
     -7:48.1.0 markdown-preview-plus:sync-preview (atom-text-editor.editor.is-focused)
     -7:43.1.0 encoding-selector:show (atom-text-editor.editor.is-focused)
     -7:38.4.0 git-control:toggle (atom-text-editor.editor.is-focused)
     -4:04.1.0 core:move-left (atom-text-editor.editor.is-focused)
 13x -4:03.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:59.8.0 core:undo (atom-text-editor.editor.is-focused)
```

**Comment by nagim** [comment]
Awesome, thanks! Will test it soon!
